{% set name = "cox" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa7828d4b3e6b2327870e11117642e7dfe349ef2532927ad22c30ea6e4bd1c29

build:
  noarch: python
  number: 0
  entry_points:
    - cox-tensorboard=cox.tensorboard_view:main
  script: {{ PYTHON }} -m pip install .  -vv

requirements:
  host:
    - pip
    - python
  run:
    - gitpython
    - grpcio
    - psutil
    - py3nvml
    - python
    - tqdm
    - pandas
    - pytorch
    - dill
    - tensorboardx

test:
  imports:
    - cox
  commands:
    - cox-tensorboard --help

about:
  home: https://github.com/MadryLab/cox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Tools for Experiment Logging"
  doc_url: https://cox.readthedocs.io/en/latest/
  dev_url: https://github.com/MadryLab/cox

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
